# Generated by Django 2.2 on 2021-10-09 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ceres_report',
            old_name='reports',
            new_name='text',
        ),
    ]
